import { useState } from 'react';
import { LayoutDashboard, User, GraduationCap, BriefcaseBusiness, BrainCircuit, FolderKanban, Award, FileText, Mail, MessageCircle, MapPin, Menu, X, ArrowUpRight, BookOpen, Target, Sparkles } from 'lucide-react';
import { PORTFOLIO_OWNER, SKILLS_LIST } from './data/portfolioData';

const nav = [
  ['Overview','home',LayoutDashboard],['About','about',User],['Education','education',GraduationCap],['Experience','experience',BriefcaseBusiness],['Skills','skills',BrainCircuit],['Projects','projects',FolderKanban],['Certificates','certificates',Award],['Contact','contact',Mail]
] as const;

export function App(){
 const [open,setOpen]=useState(false);
 return <div className="min-h-screen bg-[#f5f7fb] text-slate-900 lg:flex">
  <aside className={`fixed inset-y-0 left-0 z-50 w-72 bg-[#071a33] text-white p-6 transition-transform lg:translate-x-0 ${open?'translate-x-0':'-translate-x-full'}`}>
   <div className="flex items-center justify-between mb-10"><a href="#home" className="font-display font-extrabold text-2xl">ALMASI<span className="text-[#f4b400]">.</span></a><button className="lg:hidden" onClick={()=>setOpen(false)}><X/></button></div>
   <div className="rounded-2xl bg-white/5 border border-white/10 p-4 mb-7"><div className="w-14 h-14 rounded-2xl bg-[#f4b400] text-[#071a33] grid place-items-center text-xl font-extrabold mb-3">AI</div><div className="font-bold">Almasi Ibrahimu</div><div className="text-xs text-slate-400 mt-1">Economics • Finance • Data</div></div>
   <nav className="space-y-1">{nav.map(([label,id,Icon])=><a key={id} href={`#${id}`} onClick={()=>setOpen(false)} className="flex items-center gap-3 px-4 py-3 rounded-xl text-sm text-slate-300 hover:bg-white/10 hover:text-white transition"><Icon className="w-4 h-4"/>{label}</a>)}</nav>
   <div className="absolute bottom-6 left-6 right-6 text-xs text-slate-500">AlmasiIbrahimu.com<br/>Personal Dashboard</div>
  </aside>

  <main className="lg:ml-72 w-full">
   <header className="sticky top-0 z-40 h-16 bg-white/90 backdrop-blur border-b flex items-center justify-between px-5 md:px-10"><button className="lg:hidden" onClick={()=>setOpen(true)}><Menu/></button><div className="hidden lg:block text-sm text-slate-500">Personal Dashboard <span className="mx-2">/</span> Overview</div><a href={`https://wa.me/${PORTFOLIO_OWNER.whatsappNumber}`} target="_blank" className="ml-auto flex items-center gap-2 bg-[#071a33] text-white px-4 py-2 rounded-xl text-sm font-semibold"><MessageCircle className="w-4 h-4"/> Connect</a></header>

   <div className="max-w-7xl mx-auto p-5 md:p-10 space-y-8">
    <section id="home" className="scroll-mt-24 grid xl:grid-cols-[1.6fr_.8fr] gap-6">
     <div className="relative overflow-hidden rounded-3xl bg-[#071a33] text-white p-8 md:p-12"><div className="absolute inset-0 bg-tech-grid-dark opacity-60"/><div className="relative"><span className="inline-flex items-center gap-2 text-xs font-semibold bg-white/10 border border-white/10 rounded-full px-3 py-1.5 mb-7"><span className="w-2 h-2 rounded-full bg-emerald-400"/> Building my professional journey</span><p className="text-[#f4b400] font-semibold mb-2">HELLO, I'M</p><h1 className="text-4xl md:text-6xl font-extrabold tracking-tight mb-4">Almasi Ibrahimu</h1><p className="text-lg md:text-xl text-slate-300 max-w-2xl leading-relaxed">Economics & Finance student, business professional, and aspiring data scientist focused on turning business experience into data-driven impact.</p><div className="flex flex-wrap gap-3 mt-8"><a href="#about" className="bg-[#f4b400] text-[#071a33] font-bold px-5 py-3 rounded-xl">Explore profile</a><a href="#contact" className="border border-white/20 px-5 py-3 rounded-xl font-semibold">Contact me</a></div></div></div>
     <div className="rounded-3xl bg-white border p-7 shadow-sm"><div className="flex justify-between"><div><p className="text-xs uppercase tracking-widest text-slate-400">Profile status</p><h3 className="font-bold text-xl mt-1">Growing & Learning</h3></div><Sparkles className="text-[#f4b400]"/></div><div className="mt-8 space-y-5"><Info icon={MapPin} label="Based in" value="Tanzania"/><Info icon={GraduationCap} label="Academic focus" value="Economics & Finance"/><Info icon={Target} label="Career direction" value="Data Science"/><Info icon={BookOpen} label="Current mode" value="Learning + Practical Work"/></div></div>
    </section>

    <section id="about" className="scroll-mt-24 grid lg:grid-cols-3 gap-6"><Card className="lg:col-span-2"><Tag>ABOUT ME</Tag><h2 className="section-title">A business mind moving toward data.</h2><p className="body-text">I am interested in economics, finance, business management, technology and data science. My practical experience has helped me understand how sales, inventory, customer service and day-to-day business operations connect.</p><p className="body-text mt-4">My long-term goal is to build strong capabilities in data analysis, artificial intelligence and data science, and use them to solve real business problems.</p></Card><Card><Tag>CAREER GOAL</Tag><div className="mt-5 w-12 h-12 rounded-2xl bg-amber-50 grid place-items-center"><Target className="text-amber-600"/></div><h3 className="font-bold text-xl mt-5">Become a Data Scientist</h3><p className="body-text mt-2">Building from economics, finance and practical business experience toward analytics, AI and data science.</p></Card></section>

    <section id="education" className="scroll-mt-24"><Heading eyebrow="EDUCATION" title="Academic foundation"/><Card><div className="flex gap-5"><div className="w-12 h-12 shrink-0 rounded-2xl bg-blue-50 grid place-items-center"><GraduationCap className="text-blue-700"/></div><div><h3 className="font-bold text-xl">Institute of Finance Management (IFM)</h3><p className="text-slate-500 mt-1">Economics & Finance • Dar es Salaam, Tanzania</p><p className="body-text mt-4">Developing knowledge in economics, finance, quantitative thinking and business decision-making while building practical professional experience.</p></div></div></Card></section>

    <section id="experience" className="scroll-mt-24"><Heading eyebrow="EXPERIENCE" title="Practical business exposure"/><div className="grid md:grid-cols-2 xl:grid-cols-4 gap-4">{['Inventory Management','Sales & Customer Service','Marketing','Business Operations'].map((x,i)=><Card key={x}><div className="text-xs text-slate-400 font-mono">0{i+1}</div><h3 className="font-bold text-lg mt-6">{x}</h3><p className="text-sm text-slate-500 mt-2 leading-6">Hands-on experience supporting real day-to-day business activities, customer needs and operational decisions.</p></Card>)}</div></section>

    <section id="skills" className="scroll-mt-24"><Heading eyebrow="SKILLS" title="Capabilities I am developing"/><div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-4">{SKILLS_LIST.slice(0,9).map(s=><Card key={s.name}><div className="flex items-center justify-between"><h3 className="font-bold">{s.name}</h3><span className="text-[10px] font-semibold bg-slate-100 rounded-full px-2 py-1">{s.level}</span></div><p className="text-sm text-slate-500 mt-3 leading-6">{s.description}</p></Card>)}</div></section>

    <section id="projects" className="scroll-mt-24"><Heading eyebrow="PROJECTS" title="Work I will share here"/><Coming icon={FolderKanban} title="Projects Coming Soon" text="I am currently building my skills and practical work. Completed projects will be published here as my portfolio grows."/></section>
    <section id="certificates" className="scroll-mt-24 grid lg:grid-cols-2 gap-6"><div><Heading eyebrow="CERTIFICATES" title="Credentials"/><Coming icon={Award} title="Certificates Coming Soon" text="Professional courses and verified learning credentials will appear here as they are completed."/></div><div><Heading eyebrow="CV / RESUME" title="Professional profile"/><Coming icon={FileText} title="CV Coming Soon" text="My downloadable professional CV will be available here once the final version is ready."/></div></section>

    <section id="contact" className="scroll-mt-24 rounded-3xl bg-[#071a33] text-white p-8 md:p-12"><Tag light>CONTACT</Tag><div className="grid lg:grid-cols-2 gap-10 mt-4"><div><h2 className="text-3xl md:text-4xl font-extrabold">Let’s connect.</h2><p className="text-slate-300 mt-4 max-w-lg leading-7">For professional opportunities, collaboration, learning, or business conversations, you can reach me directly.</p></div><div className="space-y-3"><a href={`mailto:${PORTFOLIO_OWNER.email}`} className="flex items-center justify-between bg-white/5 border border-white/10 rounded-2xl p-4 hover:bg-white/10"><span className="flex items-center gap-3"><Mail className="w-5 h-5 text-[#f4b400]"/><span><small className="block text-slate-400">Email</small>{PORTFOLIO_OWNER.email}</span></span><ArrowUpRight/></a><a href={`https://wa.me/${PORTFOLIO_OWNER.whatsappNumber}`} target="_blank" className="flex items-center justify-between bg-[#f4b400] text-[#071a33] rounded-2xl p-4 font-semibold"><span className="flex items-center gap-3"><MessageCircle className="w-5 h-5"/>WhatsApp</span><ArrowUpRight/></a></div></div></section>
    <footer className="text-center text-xs text-slate-400 py-4">© {new Date().getFullYear()} Almasi Ibrahimu • Personal Dashboard</footer>
   </div>
  </main>
 </div>
}

function Card({children,className=''}:{children:React.ReactNode,className?:string}){return <div className={`rounded-3xl bg-white border border-slate-200/80 p-6 md:p-7 shadow-sm ${className}`}>{children}</div>}
function Tag({children,light=false}:{children:React.ReactNode,light?:boolean}){return <div className={`text-xs font-bold tracking-[.18em] ${light?'text-[#f4b400]':'text-blue-800'}`}>{children}</div>}
function Heading({eyebrow,title}:{eyebrow:string,title:string}){return <div className="mb-5"><Tag>{eyebrow}</Tag><h2 className="section-title">{title}</h2></div>}
function Info({icon:Icon,label,value}:{icon:any,label:string,value:string}){return <div className="flex gap-3 items-center"><div className="w-10 h-10 rounded-xl bg-slate-50 grid place-items-center"><Icon className="w-4 h-4 text-slate-600"/></div><div><div className="text-xs text-slate-400">{label}</div><div className="text-sm font-semibold">{value}</div></div></div>}
function Coming({icon:Icon,title,text}:{icon:any,title:string,text:string}){return <div className="rounded-3xl border border-dashed border-slate-300 bg-white p-10 text-center"><div className="w-16 h-16 mx-auto rounded-2xl bg-slate-50 grid place-items-center"><Icon className="w-7 h-7 text-slate-400"/></div><span className="inline-block mt-5 text-[10px] font-bold tracking-widest bg-amber-50 text-amber-700 px-3 py-1 rounded-full">COMING SOON</span><h3 className="font-bold text-xl mt-3">{title}</h3><p className="text-sm text-slate-500 leading-6 max-w-md mx-auto mt-2">{text}</p></div>}
